# Generated by Django 5.2.10 on 2026-02-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_migrate_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='legacy_todo_id',
        ),
    ]
